name: build

on:
  push:
    branches:
      - main
      - dev*
      - v[0-9]+.[0-9]+.[0-9]+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.0', '3.1', '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@v4
      - name: Install BLAS and LAPACK
        run: sudo apt-get install -y libopenblas-dev liblapacke-dev
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        run: bash rumale-test.sh
